#!/bin/bash

# This script oringally by:
# automatically change configuration of Mac OS X based on location
# author: Onne Gorter <o.gorter@gmail.com>
# url: http://tech.inhelsinki.nl/locationchanger/
# version: 0.4
# Abused by gwk@gwk.ca 

# redirect all IO to /dev/null (comment this out if you want to debug)
exec 1>/dev/null 2>/dev/null

# get a little breather before we get data for things to settle down
sleep 2

# get various system information
SSID=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I\
 | grep ' SSID:' | cut -d ':' -f 2 | tr -d ' '`

LOCATION=

# locations (use to be used Location name here)
ATHOME=Home

# detect HOME
ATHOME_SSID=YOUR SSID HERE

if [ -z $LOCATION ]; then
	case $SSID in
		$ATHOME_SSID	) LOCATION="$ATHOME";;
	esac
        REASON=SSID
fi

if [ -z $LOCATION ]; then
	# still didn't get a location, so do automatic
	LOCATION="automatic"
        REASON=Fallback
fi

case $LOCATION in
	$ATHOME )
		# do some stuff here if you want to
		#scselect $ATHOME
		/Library/LaunchAgents/OnlyVPN/Firewall.athome
	;;

	automatic )
		# do some stuff here if you want to
		#scselect Automatic
		/Library/LaunchAgents/OnlyVPN/Firewall.onlyvpn
	;;
	
esac

# do some stuff here that needs to happen after every network change

echo `date` "Location: $LOCATION " >> /var/log/OnlyVPN.log

exit 0
